---
title: "Homework 4"
author: "Camila Ramírez"
date: "30/10/2021"
output: pdf_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
list.of.packages <- c("tidyverse", "descr", "broom", "ivpack", "MASS", "broom", 
                      "finalfit", "labelled", "dplyr", "stargazer", "survay", "ggplot2")
library(tidyverse)
library(descr)
library(broom)
library(ivpack)
library(MASS)
library(broom)
library(finalfit)
library(labelled)
library(dplyr)
library(stargazer)
library(ggplot2)
library(questionr)
library(knitr)

new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

setwd("~/PSE/Measurement of PO/Homework 4")
library(haven)
data <- read_dta("civ_87_08.dta")
View(data)
```

# c)

```{r, warnings = FALSE}
data$conspercapita <- data$constot/data$hhsize
identical(data$conspc, data$conspercapita)
dif <- data$conspercapita - data$conspc
summary(dif)
```

#  d) 

```{r, warnings = FALSE}
data$logpc <- log(data$conspercapita)
hist(data$logpc,
     main="Histogram for Logarithm of consumption per capita",
     xlab="")
hist(data$conspercapita,
     main= "Histogram for consumption per capita",
     xlab="")
```

```{r, warnings = FALSE}

median1 <- median(data$logpc[data$year==1987])
sd1 <- sd(data$logpc[data$year==1987])

data$outlier2 <- ifelse((abs(data$logpc - median1)> 3*sd1 & data$year==1987 |  
                     abs(data$logpc - median2)> 3*sd2 & data$year==1998 |
                     abs(data$logpc - median3)> 3*sd3 & data$year==2008), 1, 0)
sum(data$outlier2)/length(data$outlier2)

data$diferentes <- ifelse(data$outlier==data$outlier2, 0, 1)
sum(data$diferentes)

cleardata <- subset(data, data$outlier2==0)

```

## PART 2

# a)

```{r, warnings = FALSE}


describe(cleardata$femalehead)

cleardata$representative <- ifelse((cleardata$hhsize==4 & cleardata$femalehead==0 
                           & (cleardata$work_farmer==1 | cleardata$work_selfem == 1)), 1, 0)

#Share of food expenditure in the household consumption:

cleardata$sharefood <- cleardata$exp_food/cleardata$constot

#Build the weight:

cleardata$weight2 <- cleardata$hhsize*cleardata$weight*cleardata$conspercapita

#Calculate the weighted average of the share of food expenditure:

weighted.mean(cleardata$sharefood[cleardata$representative==1 & cleardata$north==0],
              cleardata$weight2[cleardata$representative==1 & cleardata$north==0])
weighted.mean(cleardata$sharefood[cleardata$representative==1 & cleardata$north==1], 
              cleardata$weight2[cleardata$representative==1 & cleardata$north==1])
cleardata$year <- as.factor(cleardata$year)

reg1 <- lm(cleardata$sharefood[cleardata$north==0 & cleardata$representative==1] ~ 
             cleardata$year[cleardata$north==0 & cleardata$representative==1] -1,
           weights=cleardata$weight2[cleardata$north==0 & cleardata$representative==1])
tidy(reg1)

reg2 <- lm(cleardata$sharefood[cleardata$north==1 & cleardata$representative==1] ~ 
             cleardata$year[cleardata$north==1 & cleardata$representative==1] -1,
           weights=cleardata$weight2[cleardata$north==1 & cleardata$representative==1])
tidy(reg2)

matrix_foodS <- as.vector(reg1$coefficients)
matrix_nofoodS <- as.vector(1-matrix_foodS)

matrix_foodN <- as.vector(reg2$coefficients)
matrix_nofoodN <- as.vector(1-matrix_foodN)

table1 <- as.table(rbind(matrix_foodS, matrix_nofoodS))
colnames(table1) <- NULL
rownames(table1) <- c("Food share for South", "Non food share for South")
table2 <- as.table(rbind(matrix_foodN, matrix_nofoodN))
colnames(table2) <- c("1987","1998","2008")
rownames(table2) <- c("Food share for North", "Non food share for North")

table3 <- kable(
  rbind(table2, table1),
  caption = "Food and non food budget shares in Côte d'Ivoire from 1987 to 2008",
  align = c('c', 'c', 'c'),
  digits = 3)

table3

```

# b)

```{r, warnings = FALSE}

#LASPEYRES

cleardata$laspeyres <- ifelse(cleardata$north==1,
  (sharefood1987N*cleardata$avprice_food/pricesfood1987N+
     sharenonfood1987N*cleardata$avprice_othr/pricesnonfood1987N)/100, 
  (sharefood1987S*cleardata$avprice_food/pricesfood1987S+
     sharenonfood1987S*cleardata$avprice_othr/pricesnonfood1987S)/100)
    
    
#Results of Laspeyres for the North:
reg3 <- lm(cleardata$laspeyres[cleardata$north==1] ~ cleardata$year[cleardata$north==1] -1)
tidy(reg3)
#Results of Laspeyres for the South:
reg4 <- lm(cleardata$laspeyres[cleardata$north==0] ~ cleardata$year[cleardata$north==0] -1)
tidy(reg4)

#Display the results as a table:

matrix_2 <- as.vector(reg3$coefficients*100)
matrix_3 <- as.vector(reg4$coefficients*100)

table_laspeyres <- as.table(rbind(matrix_2, matrix_3))
colnames(table_laspeyres) <- c("1987","1998","2008")
rownames(table_laspeyres) <- c("Laspeyres index for North", "Laspeyres index for South")
table_laspeyres <- kable(
  table_laspeyres,
  caption = "Laspeyres CPI across regions",
  align = c('c', 'c', 'c'),
  digits = 3)

table_laspeyres

#PAASCHE:

cleardata$paasche <- 
  ifelse(cleardata$north==1, 1/(cleardata$bdgshr_food/100*(pricesfood1987N/cleardata$avprice_food)+
                                cleardata$bdgshr_othr/100*(pricesnonfood1987N/cleardata$avprice_othr)),
         1/(cleardata$bdgshr_food/100*(pricesfood1987S/cleardata$avprice_food)+
                                cleardata$bdgshr_othr/100*(pricesnonfood1987S/cleardata$avprice_othr)))


#Results of Paasche for the North:
reg5 <- lm(cleardata$paasche[cleardata$north==1] ~ cleardata$year[cleardata$north==1] -1)
tidy(reg5)
#Results of Paasche for the South:
reg6 <- lm(cleardata$paasche[cleardata$north==0] ~ cleardata$year[cleardata$north==0] -1)
tidy(reg6)

#I display the results as a table:

matrix_5 <- as.vector(reg5$coefficients*100)
matrix_6 <- as.vector(reg6$coefficients*100)

table_paasche <- as.table(rbind(matrix_5, matrix_6))
colnames(table_paasche) <- c("1987","1998","2008")
rownames(table_paasche) <- c("Paasche index for North", "Paasche index for South")
table_paasche <- kable(
  table_paasche,
  caption = "Paasche CPI across regions",
  align = c('c', 'c', 'c'),
  digits = 3)

table_paasche


```

#  c)


```{r, warnings = FALSE}

library(kableExtra)

table_PPP <- as.table(rbind(laspeyres.vector, paasche.vector, fisher.vector))
colnames(table_PPP) <- c("1987","1998","2008")
rownames(table_PPP) <- c("Laspeyres", "Paasche", "Fisher")
table_PPP <- kable(
  table_PPP,
  caption = "PPP for the North with respect to the South, 
  with Laspeyres, Paasche and Fisher methods. ",
  align = c('c', 'c', 'c'),
  digits = 3)


table_PPP

```

# d)

```{r, warnings = FALSE}
# First, I transform the consumption taking into account inflation:

cleardata$conspc87_2 <- cleardata$conspc/(cleardata$cpi)

#Then, I transform the consumption taking into account regional differences in prices, with PPP:

cleardata$conspcsouth87 <- ifelse(cleardata$north==1, 
                                  (cleardata$conspc87_2)/cleardata$ppp, cleardata$conspc87_2)

summary(cleardata$conspcsouth87-cleardata$conspc87)

```

## PART 3

# a) 

Calculate the poverty headcount rate over time, across regions and at the national level.

```{r, warnings = FALSE}
cleardata$poor <- ifelse(cleardata$conspc87< 237, 1, 0)

cleardata$weight3 <- cleardata$hhsize*cleardata$weight

#1987:
generalpoverty1987 <- weighted.mean(cleardata$poor[cleardata$year==1987], 
                                    cleardata$weight3[cleardata$year==1987])

poverty_north_1987 <- weighted.mean(cleardata$poor[cleardata$north==1
                                                   & cleardata$year==1987], 
                                    cleardata$weight3[cleardata$north==1
                                                      & cleardata$year==1987])
poverty_south_1987 <- weighted.mean(cleardata$poor[cleardata$north==0 
                                                   & cleardata$year==1987], 
                                    cleardata$weight3[cleardata$north==0 
                                                      & cleardata$year==1987])

poverty1987.vector <- c(generalpoverty1987, poverty_north_1987, poverty_south_1987)


table_poverty <- as.table(rbind(poverty1987.vector, poverty1998.vector, 
                                poverty2008.vector))
colnames(table_poverty) <- c("National level","North","South")
rownames(table_poverty) <- c("1987", "1998", "2008")
table_poverty <- kable(
  table_poverty,
  caption = "Poverty rates per year and per region",
  align = c('c', 'c', 'c'),
  digits = 3)


table_poverty


```

# b)

```{r, warnings = FALSE}

table(cleardata$cpi)

cleardata$cpi2 <- ifelse(cleardata$year==1987, 1,
                  ifelse(cleardata$year==1998, 1.9245, 2.5573))
```

```{r, warnings = FALSE}
cleardata$newconspc87 <- cleardata$conspc/cleardata$cpi2
cleardata$poor2 <- ifelse(cleardata$newconspc87 < 237, 1, 0)

#1987:
generalpoverty1987_2 <- weighted.mean(cleardata$poor2[cleardata$year==1987], 
                                    cleardata$weight3[cleardata$year==1987])

poverty_north_1987_2 <- weighted.mean(cleardata$poor2[cleardata$north==1
                                                   & cleardata$year==1987], 
                                    cleardata$weight3[cleardata$north==1
                                                      & cleardata$year==1987])
poverty_south_1987_2 <- weighted.mean(cleardata$poor2[cleardata$north==0 
                                                   & cleardata$year==1987], 
                                    cleardata$weight3[cleardata$north==0 
                                                      & cleardata$year==1987])

poverty1987.vector2 <- c(generalpoverty1987_2, poverty_north_1987_2, 
                         poverty_south_1987_2)

 
```

## EXERCISE 4

# a)


```{r, warnings = FALSE}

library(spatstat)
cleardata$weight3 <- cleardata$weight*cleardata$hhsize

f1 <- ewcdf(cleardata$conspc87[cleardata$year==1987], 
            cleardata$weight3[cleardata$year==1987])

f2 <- ewcdf(cleardata$conspc87[cleardata$year==1998], 
            cleardata$weight3[cleardata$year==1998])

f3 <- ewcdf(cleardata$conspc87[cleardata$year==2008], 
            cleardata$weight3[cleardata$year==2008])

q <- seq(from = 0.01, to = 1, by = 0.01)
quantiles1987 <- quantile.ewcdf(f1, probs = q)
quantiles1998 <- quantile.ewcdf(f2, probs = q)
quantiles2008 <- quantile.ewcdf(f3, probs = q)

  
cleardata$percentile <- ifelse(cleardata$year==1987, 
                               ceiling(100*f1(cleardata$conspc87)), NA)
cleardata$percentile <- ifelse(cleardata$year==1998, 
                               ceiling(100*f2(cleardata$conspc87)), cleardata$percentile)
cleardata$percentile <- ifelse(cleardata$year==2008, 
                               ceiling(100*f3(cleardata$conspc87)), cleardata$percentile)

                      
```

# b)

```{r, warnings = FALSE}

#For 1998:

conspc1998 <- vector("numeric")

for(i in 1:100) {
b <- weighted.mean(cleardata$conspc87[cleardata$year==1998 & cleardata$percentile==i], 
                              cleardata$weight3[cleardata$year==1998 & cleardata$percentile==i])
conspc1998 <- c(conspc1998, b)
}

#For 1987:

conspc1987 <- vector("numeric")

for(i in 1:100) {
bb <- weighted.mean(cleardata$conspc87[cleardata$year==1987 & cleardata$percentile==i], 
                              cleardata$weight3[cleardata$year==1987 & cleardata$percentile==i])
conspc1987 <- c(conspc1987, bb)
}


# For 2008:
conspc2008 <- vector("numeric")

for(i in 1:100) {
bbb <- weighted.mean(cleardata$conspc87[cleardata$year==2008 & cleardata$percentile==i], 
                              cleardata$weight3[cleardata$year==2008 & cleardata$percentile==i])
conspc2008 <- c(conspc2008, bbb)
}


# Average growth rate of consumption per capita per year, per percentile:

averagegrowth1998 <- ((conspc1998/conspc1987)^(1/11) - 1)*100

averagegrowth2008 <- ((conspc2008/conspc1998)^(1/10) - 1)*100

p <- 1:100; p

datagrowth<- data.frame(conspc1987, conspc1998, conspc2008, averagegrowth1998, averagegrowth2008, p)

```

## c)

Draw the two curves on the same graph.

```{r, warnings = FALSE}

plot1 <- 
  ggplot(datagrowth, aes(x=p), theme_classical()) +
  geom_line(aes(y = averagegrowth1998, color = "darkred"), size=1) + 
  geom_line(aes(y = averagegrowth2008, color="navyblue"), size=1) +
  theme_bw() +
  ggtitle("Growth Incidence Curves, 1987-1998 and 1998-2008") +
  labs(x = "Consumption per capita percentiles", y = "Average annual growth, %",
       caption = "
    Average annual growth rate per percentile of consumption per capita. 
    Data extracted from a repeated survey on living standards in Cote d’Ivoire in 1987, 1998 and 2008.
    Per capita consumption is measured in constant 1987 franc CFA") +
  theme(plot.title=element_text( hjust=0.4, vjust=0, face='bold'),
        plot.caption = element_text(hjust = 0)) +
  scale_color_discrete(name = "Period", labels = c("1987-1998", "1998-2008"))




plot1

```

